package tz.co.nlolo.lifeplatform.accumulation;

/**
 * Every migration a fixed-term deposit's path reaches, in order: issuance (policy, underwriting,
 * party, product with its grid), billing's single-premium invoice, the payment rail, and the
 * account with its terms. One list for every deposit test class, rather than another copy to miss
 * the next migration in.
 *
 * <p>Public since product step 4: the bonus module's tests use it too, so it carries bonus V1 and
 * policy V32.
 */
public final class DepositTestMigrations {
    private DepositTestMigrations() {}

    public static final String[] ALL = {
        "db-migrations/party/V1__create_party_schema.sql",
        "db-migrations/party/V2__individual_person_record.sql",
        "db-migrations/party/V4__registered_by_agent.sql",
        "db-migrations/party/V5__registered_by_name.sql",
        "db-migrations/party/V6__client_reference.sql",
        "db-migrations/product/V1__create_product_schema.sql",
        "db-migrations/product/V2__base_rate_table.sql",
        "db-migrations/product/V3__base_rate_structured_age.sql",
        "db-migrations/product/V4__rating_table_unique_band.sql",
        "db-migrations/product/V5__rating_table_age_bounds.sql",
        "db-migrations/product/V6__eligibility_bounds.sql",
        "db-migrations/product/V9__rating_table_sum_assured_bounds.sql",
        "db-migrations/product/V10__ifrs_measurement_model_on_version.sql",
        "db-migrations/product/V11__frequency_loading.sql",
        "db-migrations/product/V12__tira_filing.sql",
        "db-migrations/product/V13__benefit_calculation_method.sql",
        "db-migrations/product/V15__exclusion_periods.sql",
        "db-migrations/product/V16__base_rate_term_bands.sql",
        "db-migrations/product/V17__cash_value.sql",
        "db-migrations/product/V18__payout_schedule.sql",
        "db-migrations/product/V19__accumulation_terms.sql",
        "db-migrations/product/V20__deposit_rate_grid.sql",
        "db-migrations/product/V21__bonus_terms.sql",
        "db-migrations/product/V27__ifrs17_classification.sql",
        "db-migrations/product/V28__survival_investment_component.sql",
        "db-migrations/accumulation/V1__create_accumulation_schema.sql",
        "db-migrations/accumulation/V2__request_keys.sql",
        "db-migrations/accumulation/V3__deposit_periods.sql",
        "db-migrations/bonus/V1__create_bonus_schema.sql",
        "db-migrations/benefitpayout/V1__create_benefitpayout_schema.sql",
        "db-migrations/benefitpayout/V2__annuity_streams.sql",
        "db-migrations/benefitpayout/V3__withholding.sql",
        "db-migrations/benefitpayout/V4__withholding_rule_end.sql",
        "db-migrations/underwriting/V1__create_underwriting_schema.sql",
        "db-migrations/underwriting/V2__agent_of_record.sql",
        "db-migrations/underwriting/V3__medical_disclosure_recorded_by.sql",
        "db-migrations/underwriting/V4__proposal_identity.sql",
        "db-migrations/underwriting/V5__explicit_decision.sql",
        "db-migrations/underwriting/V6__proposal_terms_and_beneficiaries.sql",
        "db-migrations/underwriting/V8__rating_multiplier.sql",
        "db-migrations/underwriting/V9__group_proposal.sql",
        "db-migrations/underwriting/V10__issuance_failure.sql",
        "db-migrations/underwriting/V11__member_evidence_case.sql",
        "db-migrations/underwriting/V18__sale_channel_and_branch.sql",
        "db-migrations/refdata/V1__create_refdata_schema.sql",
        "db-migrations/refdata/V2__seed_policy_loan_parameters.sql",
        "db-migrations/refdata/V8__ifrs17_branches_and_channels.sql",
        "db-migrations/policy/V1__create_policy_schema.sql",
        "db-migrations/policy/V2__endorsement_append_only_and_money_checks.sql",
        "db-migrations/policy/V3__premium_fields.sql",
        "db-migrations/policy/V4__underwriting_case_id.sql",
        "db-migrations/policy/V5__beneficiary_party_index.sql",
        "db-migrations/policy/V6__policy_term.sql",
        "db-migrations/policy/V7__life_assured.sql",
        "db-migrations/policy/V10__one_policy_per_underwriting_case.sql",
        "db-migrations/policy/V11__not_taken_up_status.sql",
        // V18 is what lets a policy be SINGLE -- a deposit is one -- and it sits on the scheme run.
        "db-migrations/policy/V8__group_policies_have_no_single_life_assured.sql",
        "db-migrations/policy/V9__group_scheme_and_members.sql",
        "db-migrations/policy/V13__freeform_members.sql",
        "db-migrations/policy/V14__credit_life_scheme.sql",
        "db-migrations/policy/V15__enrolment_submission.sql",
        "db-migrations/policy/V16__insurer_issued_member_reference.sql",
        "db-migrations/policy/V17__enrolment_row_member_reference.sql",
        "db-migrations/policy/V18__scheme_premium_rate.sql",
        "db-migrations/policy/V19__enrolment_premium.sql",
        "db-migrations/policy/V20__member_exit_reason.sql",
        "db-migrations/policy/V22__member_promoted_party.sql",
        "db-migrations/policy/V23__member_open_death_claim.sql",
        "db-migrations/policy/V24__issuance_record.sql",
        "db-migrations/policy/V25__credit_life_premium_basis.sql",
        "db-migrations/policy/V26__enrolment_stated_premium.sql",
        "db-migrations/policy/V27__expired_status.sql",
        "db-migrations/policy/V28__policies_due_to_expire.sql",
        "db-migrations/policy/V29__paid_up.sql",
        "db-migrations/policy/V30__surrender.sql",
        "db-migrations/policy/V31__free_look_status.sql",
        "db-migrations/policy/V32__attached_bonus_projection.sql",
        "db-migrations/policy/V37__sale_classification.sql",
        "db-migrations/audit/V1__create_audit_schema.sql",
        "db-migrations/audit/V2__rls_fail_closed.sql",
        "db-migrations/audit/V3__q4_2026_partitions.sql",
        "db-migrations/payment/V1__create_payment_schema.sql",
        "db-migrations/payment/V2__grants_rls_money_checks_version_and_tenant_scoped_registries.sql",
        "db-migrations/payment/V6__disbursement_method.sql",
        "db-migrations/payment/V7__q4_2026_partitions.sql",
        "db-migrations/payment/V8__benefit_payout_purposes.sql",
        "db-migrations/payment/V9__account_purposes.sql",
        "db-migrations/payment/V10__deposit_maturity_purpose.sql",
        "db-migrations/policyloan/V1__create_policyloan_schema.sql",
        "db-migrations/policyloan/V3__money_check_constraints.sql",
        "db-migrations/policyloan/V4__persist_reservation_id.sql",
        "db-migrations/policyloan/V5__loan_interest_accrual.sql",
        "db-migrations/policyloan/V7__q4_2026_partitions.sql",
        "db-migrations/policyloan/V8__interest_month_published.sql",
        "db-migrations/billing/V1__create_billing_schema.sql",
        "db-migrations/billing/V2__grants_rls_money_checks_and_notification_columns.sql",
        "db-migrations/billing/V3__amount_paid.sql",
        "db-migrations/billing/V5__single_premium_invoice.sql",
        "db-migrations/billing/V6__premium_credit.sql",
        "db-migrations/billing/V7__policy_inception_invoice.sql",
        "db-migrations/billing/V8__schedule_premium_paying_until.sql",
        "db-migrations/billing/V9__schedules_due_for_invoicing.sql",
    };
}
