/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/policies/{policyNumber}/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List outstanding invoices for a policy */
        get: {
            parameters: {
                query?: {
                    status?: "DUE" | "PARTIALLY_PAID" | "PAID" | "IN_GRACE" | "OVERDUE" | "WAIVED";
                };
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceView"][];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/invoices/next-due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightweight "what do I owe?" lookup (Deliverable 3 Rev 2, Bi2 — built for USSD) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceView"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Policy not found, or no invoice currently due for it */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoiceId}/waiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Waive an invoice (staff only — reason is mandatory and audit-relevant) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invoiceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Invoice waived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoiceId}/payment-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request collection of an invoice's premium through payment (staff/agent)
         * @description Publishes billing.PaymentRequested (request/confirm pattern) — payment attempts collection against payerRef and, on success, publishes payment.PaymentConfirmed, which billing's own PaymentEventListener consumes to move the invoice toward PARTIALLY_PAID/PAID. Customers may request payment only for an invoice belonging to their own policy (object-level check against the token's party_id claim); agents and staff are scoped to their tenant.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key identifying this collection ATTEMPT, not the invoice. Reusing a key is deduplicated by payment, so a double-submit is safe; supplying a NEW key starts a new attempt, which is what makes an operator retry after a decline (or a PARTIALLY_PAID top-up) possible at all. There is no default — a missing or blank value is a 400, because any default would either make retry impossible or discard duplicate protection. */
                    "Idempotency-Key": string;
                };
                path: {
                    invoiceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        payerRef: string;
                    };
                };
            };
            responses: {
                /** @description Payment requested, accepted for processing */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/field-receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture a premium receipt offline (BillingSyncApi — agent field app)
         * @description Lands as PENDING_RECONCILIATION (FieldReceiptCaptured). If unmatched by a PaymentConfirmed within the refdata-configured SLA (default 24h), escalates to FieldReceiptReconciliationOverdue (Deliverable 2 Rev 2, B4).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    agentId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        policyNumber: components["schemas"]["PolicyNumberRef"];
                        amount: components["schemas"]["Money"];
                        clientIdempotencyKey: string;
                        /**
                         * Format: date-time
                         * @description Client-device timestamp — server timestamp also recorded for reconciliation ordering.
                         */
                        capturedAt: string;
                    };
                };
            };
            responses: {
                /** @description Accepted, pending reconciliation */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            receiptId?: string;
                            /** @enum {string} */
                            status?: "PENDING_RECONCILIATION";
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InvoiceView: {
            /** Format: uuid */
            invoiceId?: string;
            policyNumber?: components["schemas"]["PolicyNumberRef"];
            /** Format: date */
            dueDate?: string;
            amount?: components["schemas"]["Money"];
            /** @enum {string} */
            status?: "DUE" | "PARTIALLY_PAID" | "PAID" | "IN_GRACE" | "OVERDUE" | "WAIVED";
            /** Format: date */
            gracePeriodEndsAt?: string | null;
            /** @description Present only when an ArrearsCase is open (Deliverable 3 Rev 2, Bi1). */
            dunningLevel?: number | null;
        };
        PolicyNumberRef: string;
        Money: {
            /** @description Decimal string — never a binary float. */
            amount: string;
            /** @example TZS */
            currencyCode: string;
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Validation failure (RFC 7807) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
