/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List claims
         * @description Customers are always scoped to their own claims regardless of any claimantPartyId supplied (docs/04-api-contracts.md §3) — agents/staff may filter by any claimantPartyId, or omit it to see all claims in their scope.
         */
        get: {
            parameters: {
                query?: {
                    status?: "REGISTERED" | "UNDER_ASSESSMENT" | "APPROVED" | "REJECTED" | "SETTLEMENT_REQUESTED" | "SETTLED" | "REOPENED";
                    /** @description Ignored, and overridden with the caller's own party_id claim, for customers-realm tokens */
                    claimantPartyId?: components["schemas"]["PartyRef"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimSearchResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Register a new claim */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key for safe retry of this registration. A repeat call with the SAME key returns the ALREADY-registered claim instead of creating a second one (claims/V3's registration-idempotency index); a DIFFERENT key is always treated as a genuinely new registration attempt, even for what might be the same real-world event. */
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterClaimRequest"];
                };
            };
            responses: {
                /** @description Claim registered, or -- on a repeated Idempotency-Key -- the already-registered claim */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimView"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description claimType inconsistent with the policy's active coverage as of dateOfEvent, or the policy is not in force, or the details payload's own claimType does not match */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{claimId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get claim detail
         * @description A customers-realm token may only read a claim whose claimantPartyId matches its own party_id claim (docs/04-api-contracts.md §3) — any other customer gets 403, not 200 and not 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimView"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{claimId}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a claim assessment (staff — CLAIMS_ASSESSOR role) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitClaimAssessmentRequest"];
                };
            };
            responses: {
                /** @description Assessment recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimAssessmentView"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Claim is not in a status that can begin assessment (must be REGISTERED or REOPENED, or already UNDER_ASSESSMENT) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{claimId}/settlement-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject the claim (staff — CLAIMS_MANAGER role only; distinct from CLAIMS_ASSESSOR) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Required on every call to this operation, but only load-bearing when approved is true: it becomes claim.settlement_idempotency_key, the value payment's own (tenant_id, idempotency_key) registry dedupes the resulting disbursement request against. */
                    "Idempotency-Key": string;
                };
                path: {
                    claimId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        approved: boolean;
                        approvedAmount?: components["schemas"]["Money"];
                        rejectionReason?: string | null;
                        /** @description Mobile-money destination for the payout. Required when approved is true; ignored (may be null) when approved is false */
                        payeeRef?: string | null;
                    };
                };
            };
            responses: {
                /** @description Decision recorded; if approved, ClaimSettlementRequested is published and settlement completes asynchronously via payment's request/confirm loop. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimView"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Claim requires at least one completed assessment first (except MATURITY, which auto-approves — Deliverable 3 Rev 2, Cl3), or is not in a status that can be decided, or is already APPROVED for a DIFFERENT approvedAmount/currency than this request carries (a settlement retry must repeat the amount already on the record; reopen the claim to change it). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description approved is true but payeeRef or Idempotency-Key is missing/blank, or the same person both assessed and is deciding this claim (separation of duties) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{claimId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen a rejected or settled claim (staff — CLAIMS_MANAGER role only)
         * @description REJECTED or SETTLED → REOPENED. Deliberately does not clear a prior approvedAmount — the previous decision stays on the record until a new one is made.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Claim reopened */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimView"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Claim is not REJECTED or SETTLED (only those two statuses can be reopened) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{claimId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List evidence attached to a claim
         * @description Same object-level ownership check as GET /claims/{claimId} — a customers-realm token may only list evidence for a claim whose claimantPartyId matches its own party_id claim.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimEvidenceView"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Attach evidence to a claim
         * @description Uploads a document (photo, certificate, report) and links it to the claim as evidence. Rejected once the claim is SETTLED — reopen it first.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description Evidence attached */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimEvidenceView"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Claim is SETTLED — reopen it before attaching evidence */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterClaimRequest: {
            policyNumber: components["schemas"]["PolicyNumberRef"];
            claimantPartyId: components["schemas"]["PartyRef"];
            /** @enum {string} */
            claimType: "DEATH" | "DISABILITY" | "CRITICAL_ILLNESS" | "MATURITY";
            /** Format: date */
            dateOfEvent: string;
            details: components["schemas"]["ClaimDetails"];
        };
        /** @description Polymorphic by claimType — modeled server-side as a sealed ClaimDetails hierarchy (Deliverable 3 Rev 2, Cl2). Deliberately NO `discriminator` keyword: verified empirically against a real swagger-request-validator 2.46.0 instance (the exact library Task 10's contract tests use) that ANY discriminator+oneOf shape here -- discriminator on the base with siblings, discriminator on the base with allOf-composed subtypes, tried both -- fails the same internal syntax check (err.swaggerv2.discriminator.wrongType) on every schema that references ClaimDetails, before a single test request is even evaluated. A bare `oneOf` with no discriminator validates correctly: each branch's claimType enum already restricts it to exactly one value, so the oneOf is unambiguous without a discriminator hint -- `discriminator` is a codegen/dispatch optimization, not a validation requirement. */
        ClaimDetails: components["schemas"]["DeathClaimDetails"] | components["schemas"]["DisabilityClaimDetails"] | components["schemas"]["CriticalIllnessClaimDetails"] | components["schemas"]["MaturityClaimDetails"];
        DeathClaimDetails: {
            /** @enum {string} */
            claimType: "DEATH";
            causeOfDeath: string;
            placeOfDeath: string;
            /** Format: date */
            dateOfDeath: string;
            attendingPhysician: string;
        };
        DisabilityClaimDetails: {
            /** @enum {string} */
            claimType: "DISABILITY";
            disabilityType: string;
            /** Format: date */
            onsetDate: string;
            permanent: boolean;
            /** @description Decimal string 0-100 — never a binary float, matching openapi-common.yaml's Money convention */
            impairmentPercent: string;
        };
        CriticalIllnessClaimDetails: {
            /** @enum {string} */
            claimType: "CRITICAL_ILLNESS";
            diagnosis: string;
            /** Format: date */
            diagnosisDate: string;
            icdCode: string;
        };
        MaturityClaimDetails: {
            /** @enum {string} */
            claimType: "MATURITY";
            /** Format: date */
            maturityDate: string;
        };
        SubmitClaimAssessmentRequest: {
            findings: string;
            recommendedAmount: components["schemas"]["Money"];
            /**
             * @description Scrutiny/reporting signal only — does not itself reject the claim (Deliverable 3 Rev 2, Cl1)
             * @default false
             */
            fraudIndicator: boolean;
        };
        ClaimAssessmentView: {
            /** Format: uuid */
            claimAssessmentId: string;
            /** Format: uuid */
            claimId: string;
            assessor: string;
            findings: string;
            recommendedAmount: components["schemas"]["Money"];
            fraudIndicator: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ClaimEvidenceView: {
            /** Format: uuid */
            claimEvidenceId: string;
            /** Format: uuid */
            claimId: string;
            documentRef: string;
            description?: string | null;
            uploadedBy: string;
            /** Format: date-time */
            uploadedAt: string;
        };
        ClaimView: {
            /** Format: uuid */
            claimId: string;
            policyNumber: components["schemas"]["PolicyNumberRef"];
            claimantPartyId: components["schemas"]["PartyRef"];
            /** @enum {string} */
            claimType: "DEATH" | "DISABILITY" | "CRITICAL_ILLNESS" | "MATURITY";
            /** @enum {string} */
            status: "REGISTERED" | "UNDER_ASSESSMENT" | "APPROVED" | "REJECTED" | "SETTLEMENT_REQUESTED" | "SETTLED" | "REOPENED";
            /** Format: date */
            dateOfEvent: string;
            details: components["schemas"]["ClaimDetails"];
            approvedAmount?: components["schemas"]["Money"];
            /** @description True when the claim falls inside the policy's contestability window and needs a non-disclosure review before approval — re-derived fresh on every read, not a stored column */
            requiresContestabilityReview: boolean;
        };
        ClaimSearchResponse: {
            items?: components["schemas"]["ClaimView"][];
            page?: components["schemas"]["PageMeta"];
        };
        /**
         * Format: uuid
         * @description Opaque PartyId. Resolved via the party module's own API; never expanded inline.
         */
        PartyRef: string;
        PolicyNumberRef: string;
        Money: {
            /** @description Decimal string — never a binary float. */
            amount: string;
            /** @example TZS */
            currencyCode: string;
        };
        PageMeta: {
            page?: number;
            pageSize?: number;
            totalElements?: number;
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Missing/invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Validation failure (RFC 7807) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
