/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        Money: {
            /** @description Decimal string — never a binary float. */
            amount: string;
            /** @example TZS */
            currencyCode: string;
        };
        /**
         * Format: uuid
         * @description Opaque PartyId. Resolved via the party module's own API; never expanded inline.
         */
        PartyRef: string;
        PolicyNumberRef: string;
        /** @description Poll target for async operations kicked off by a 202 response (e.g. surrender/maturity). */
        ProcessStatus: {
            processInstanceId?: string;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "COMPLETED" | "COMPENSATING" | "FAILED";
            errorDetails?: string | null;
            /**
             * Format: uri
             * @description Present once COMPLETED — link to the finalized resource.
             */
            resultLocation?: string | null;
        };
        PageMeta: {
            page?: number;
            pageSize?: number;
            totalElements?: number;
        };
    };
    responses: {
        /** @description Validation failure (RFC 7807) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Missing/invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Optimistic-locking conflict or state-machine violation (e.g. surrendering an already-surrendered policy). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Semantically valid request rejected by a domain invariant (e.g. beneficiary shares don't sum to 100%). */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
