/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/claims/{claimId}/evidence/{documentRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download one evidence file attached to a claim
         * @description Requires BOTH that the caller may read the claim AND that the document belongs to that claim. A document belonging to a different claim returns 404, never the file, even when the caller legitimately owns the claim named in the path.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    claimId: string;
                    documentRef: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The file. Content-Type is the media type recorded at upload, which is always one of the four listed below -- uploads are allowlisted to exactly this closed set, and application/octet-stream also covers a document whose media type is unknown or was never recorded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                        "application/pdf": string;
                        "application/octet-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download any document in the caller's tenant (staff only)
         * @description Staff-only, because staff are authorized tenant-wide and so need no object-level check. Customers and agents must use the owning aggregate's endpoint instead.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentRef: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The file. Content-Type is the media type recorded at upload, which is always one of the four listed below for anything uploaded through this platform's own endpoints; application/octet-stream also covers a document whose media type is unknown, was never recorded, or is not a parseable media type. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                        "application/pdf": string;
                        "application/octet-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentRef}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a document's metadata without transferring its content (staff only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentRef: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentMetadataView"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DocumentMetadataView: {
            documentRef: string;
            /** @description Opaque owning-aggregate reference, currently always "claim:{uuid}". Treated as opaque on purpose -- new producers will introduce new shapes, so do not parse it. */
            ownerContext: string;
            /** @enum {string} */
            documentType: "KYC_EVIDENCE" | "POLICY_DOCUMENT" | "CLAIM_EVIDENCE" | "SIGNED_FORM" | "UNDERWRITING_EVIDENCE";
            /** @description Null for documents uploaded before document/V2. */
            contentType?: string | null;
            /** @description Null for documents uploaded before document/V2. */
            fileName?: string | null;
            uploadedBy?: string | null;
            /** Format: date-time */
            uploadedAt: string;
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Missing/invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
