/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/parties/individuals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an individual (self-service signup, or agent-assisted) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterIndividualRequest"];
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartyView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/corporates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a corporate (e.g. an employer or SACCO for a group scheme) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterCorporateRequest"];
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartyView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{partyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get party detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartyView"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{partyId}/kyc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit KYC evidence and update verification status (staff-verified only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partyId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "VERIFIED" | "REJECTED" | "PENDING";
                        /** @description DocumentRef from the document module */
                        evidenceDocumentRef: string;
                    };
                };
            };
            responses: {
                /** @description KYC status updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{partyId}/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group members (paginated — never loaded as part of the group aggregate, Deliverable 3 Rev 2 Pa1) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    partyId: string;
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["GroupMembershipView"][];
                            page?: components["schemas"]["PageMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a group member */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    partyId: string;
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        memberPartyId: components["schemas"]["PartyRef"];
                    };
                };
            };
            responses: {
                /** @description Member added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterIndividualRequest: {
            fullName: string;
            /** Format: date */
            dateOfBirth: string;
            contactInfo: {
                phoneNumber?: string;
                /** Format: email */
                email?: string | null;
            };
        };
        RegisterCorporateRequest: {
            registeredName: string;
            /** @description Unique per tenant. */
            registrationNumber: string;
            contactInfo: Record<string, never>;
        };
        PartyView: {
            /** Format: uuid */
            partyId?: string;
            /** @enum {string} */
            partyType?: "INDIVIDUAL" | "CORPORATE" | "GROUP";
            /** @enum {string} */
            kycStatus?: "PENDING" | "VERIFIED" | "REJECTED";
            displayName?: string;
        };
        GroupMembershipView: {
            memberPartyId?: components["schemas"]["PartyRef"];
            /** Format: date */
            joinDate?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "REMOVED";
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        /**
         * Format: uuid
         * @description Opaque PartyId. Resolved via the party module's own API; never expanded inline.
         */
        PartyRef: string;
        PageMeta: {
            page?: number;
            pageSize?: number;
            totalElements?: number;
        };
    };
    responses: {
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
