/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/payments/{paymentRequestId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment status
         * @description Staff/agents only — REALM_CUSTOMERS is deliberately NOT admitted (see Task 8's implementation note). payment's tables store only opaque payer_ref/payee_ref and source_ref, with no party_id or policy_number column, so there is no way to perform the mandatory object-level ownership check a customer token would require (openapi-common.yaml:149-154, OWASP API #1). Admitting the realm without that check would be a Broken-Object-Level-Authorization hole; this is a deliberate contract narrowing versus an earlier design sketch, not an oversight.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paymentRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentStatusView"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/status-by-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment/disbursement status by idempotency key (Deliverable 3 Rev 2, Pay2 — for clients that lost track of the generated ID, e.g. after a dropped USSD session)
         * @description Staff/agents only — same REALM_CUSTOMERS exclusion and reason as /payments/{paymentRequestId}/status above. Resolves against BOTH ledgers (PaymentStatusView.kind says which one answered).
         */
        get: {
            parameters: {
                query: {
                    idempotencyKey: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentStatusView"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payout-batches/{batchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a settlement batch's status (Deliverable 3 Rev 2, Pay1 — commission runs, maturity batches, dividend runs) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    batchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayoutBatchView"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/mobile-money-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inbound gateway callback (Vodacom M-Pesa / Airtel Money / Tigo Pesa). Not part of the platform's own OpenAPI contract in the usual sense — each aggregator has its own callback payload shape; this endpoint is the ACL boundary translating that shape into PaymentConfirmed/PaymentFailed internally. Authenticated via the aggregator's own HMAC-SHA256 signature scheme (Task 8's MobileMoneyHmacFilter), not Keycloak — this is the one path in the whole platform's filter chain that is permitAll() for exactly this method+path, because a differently-authenticated caller, not an unauthenticated one, sits in front of it. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description hex(HMAC-SHA256(sharedSecret, "<X-MobileMoney-Timestamp>.<raw request body>")). Verified with a constant-time comparison; a mismatch is rejected without revealing which check failed. */
                    "X-MobileMoney-Signature": string;
                    /** @description Signed timestamp, checked against a bounded replay window (config: mobile-money.callback-replay-window-seconds) — a captured-and-replayed callback stops verifying once the window closes. */
                    "X-MobileMoney-Timestamp": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Acknowledged. Returned even for a well-formed callback whose gatewayReference is unrecognized or whose outcome could not be applied — a non-200 would only provoke a pointless retry (see Task 8's MobileMoneyCallbackController javadoc). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                /** @description Missing/malformed signature or timestamp header, stale timestamp (outside the replay window), or signature mismatch. Deliberately generic — the response body never says which check failed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaymentStatusView: {
            /** Format: uuid */
            id?: string;
            idempotencyKey?: string;
            /**
             * @description Which ledger answered. Always PAYMENT for /payments/{paymentRequestId}/status; either kind for /payments/status-by-key, since that lookup resolves against both ledgers.
             * @enum {string}
             */
            kind?: "PAYMENT" | "DISBURSEMENT";
            /**
             * @description Union of both ledgers' vocabularies — a payment's success status is CONFIRMED, a disbursement's is COMPLETED (see kind to know which applies). PENDING and IN_DOUBT are the two NON-terminal states, and the difference between them matters to a client: PENDING means the instruction has not reached the rail with any outcome yet, while IN_DOUBT means it did reach the rail and the outcome is unknown (a read timeout, or an acceptance carrying no gateway reference) — money may or may not have moved. An IN_DOUBT row is not final and can still resolve to CONFIRMED/COMPLETED or FAILED when the aggregator's asynchronous notification arrives, so a client must not treat it as a failure. Added in M5's final review; see db-migrations/payment/V4.
             * @enum {string}
             */
            status?: "PENDING" | "IN_DOUBT" | "CONFIRMED" | "COMPLETED" | "FAILED";
            amount?: components["schemas"]["Money"];
        };
        PayoutBatchView: {
            /** Format: uuid */
            batchId?: string;
            /** @enum {string} */
            batchType?: "COMMISSION_RUN" | "MATURITY_BATCH" | "DIVIDEND_RUN";
            /** @enum {string} */
            status?: "IN_PROGRESS" | "COMPLETED" | "PARTIAL_FAILURE";
            disbursementCount?: number;
            failedCount?: number;
        };
        Money: {
            /** @description Decimal string — never a binary float. */
            amount: string;
            /** @example TZS */
            currencyCode: string;
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Validation failure (RFC 7807) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
