/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/policies/manual-issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually issue a policy (staff exception path only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManualIssueRequest"];
                };
            };
            responses: {
                /** @description Policy issued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyView"];
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get policy detail
         * @description Customers may only fetch a policy where policyholderPartyId matches their token's party_id claim (object-level check, not just realm/role membership). Agents are scoped to policies where they are agentOfRecord or within their agency hierarchy. Staff have unrestricted read within their tenant.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyView"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search policies
         * @description Customers are force-scoped to their own policies: a client-supplied policyholderPartyId is overridden with the token's party_id claim. Agents are scoped to their agency hierarchy. Staff have unrestricted read within their tenant.
         */
        get: {
            parameters: {
                query?: {
                    policyholderPartyId?: components["schemas"]["PartyRef"];
                    status?: "PROPOSED" | "ACTIVE" | "LAPSED" | "SUSPENDED" | "SURRENDERED" | "MATURED" | "REINSTATED";
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["PolicyView"][];
                            page?: components["schemas"]["PageMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/endorsements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply an endorsement (contract amendment) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EndorsementRequest"];
                };
            };
            responses: {
                /** @description Endorsement applied */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyView"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/beneficiaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the beneficiary designation set
         * @description Enforces exactly-one-of (partyId, freeformDesignee) per beneficiary (Deliverable 3 Rev 2, Po2) and that active shares sum to 100%.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BeneficiaryInput"][];
                };
            };
            responses: {
                /** @description Beneficiaries updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Shares don't sum to 100%, or a beneficiary has both/neither of partyId and freeformDesignee */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/surrender-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quote current surrender value (does not commit to surrender)
         * @description Produces SurrenderValueCalculated internally — a quote only, per Deliverable 2 Rev 2 event catalog.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            policyNumber?: components["schemas"]["PolicyNumberRef"];
                            quotedValue?: components["schemas"]["Money"];
                            /** Format: date-time */
                            quotedAt?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/surrender": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate policy surrender (asynchronous — loan-netting choreography)
         * @description Returns 202 immediately; the actual net-of-loan disbursement completes via the Camunda process described in Deliverable 3 Rev 2 §12. Poll the returned processInstanceId via GET /policies/{policyNumber}/processes/{processInstanceId}.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Mobile money / bank payout destination */
                        payeeRef?: string;
                    };
                };
            };
            responses: {
                /** @description Surrender process started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessStatus"];
                    };
                };
                /** @description Policy not in a surrenderable state, or a LoanValueReservation is currently RESERVED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Surrender/maturity loan-netting choreography is deferred pending a workflow-engine decision (Camunda 7 is EOL; Camunda 8 needs a paid licence and a cross-tenant leak review) -- this endpoint is real, routable, and correctly secured, but returns 501 instead of 202 until that engine is chosen. Interim state, not the intended eventual behaviour (see the 202/409 responses above). */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/processes/{processInstanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll status of an async surrender/maturity process */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                    processInstanceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessStatus"];
                    };
                };
                /** @description Surrender/maturity loan-netting choreography is deferred pending a workflow-engine decision (Camunda 7 is EOL; Camunda 8 needs a paid licence and a cross-tenant leak review) -- there is no process engine to poll, so this endpoint returns 501 instead of 200 until that engine is chosen. Interim state, not the intended eventual behaviour (see the 200 response above). */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/coverage-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage status as of a given date (used by claims, staff, support) */
        get: {
            parameters: {
                query?: {
                    asOf?: string;
                };
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoverageStatusView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{policyNumber}/in-force": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightweight boolean in-force check (Deliverable 3 Rev 2, Po3) */
        get: {
            parameters: {
                query?: {
                    asOf?: string;
                };
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            inForce?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ManualIssueRequest: {
            /** Format: uuid */
            underwritingCaseId: string;
            policyholderPartyId: components["schemas"]["PartyRef"];
            /** Format: uuid */
            productVersionId: string;
            sumAssured: components["schemas"]["Money"];
            premiumAmount: components["schemas"]["Money"];
            /** Format: uuid */
            agentOfRecordId: string | null;
            /** @enum {string} */
            premiumFrequency?: "MONTHLY" | "QUARTERLY" | "ANNUALLY";
            beneficiaries?: components["schemas"]["BeneficiaryInput"][];
            /** @description Required — feeds audit. */
            reasonForManualIssue: string;
        };
        BeneficiaryInput: {
            /** @enum {string} */
            type: "PARTY" | "FREEFORM";
            partyId?: components["schemas"]["PartyRef"];
            freeformDesignee?: string | null;
            sharePercent: number;
            /** @default true */
            revocable: boolean;
        };
        EndorsementRequest: {
            endorsementType: string;
            /** Format: date */
            effectiveDate: string;
            /** @description Endorsement-type-specific change payload. */
            changes: Record<string, never>;
        };
        PolicyView: {
            policyNumber?: components["schemas"]["PolicyNumberRef"];
            policyholderPartyId?: components["schemas"]["PartyRef"];
            /** Format: uuid */
            productId?: string;
            /** Format: uuid */
            productVersionId?: string;
            /** Format: uuid */
            agentOfRecordId?: string | null;
            /** @enum {string} */
            status?: "PROPOSED" | "ACTIVE" | "LAPSED" | "SUSPENDED" | "SURRENDERED" | "MATURED" | "REINSTATED";
            /** Format: date */
            issueDate?: string;
            sumAssured?: components["schemas"]["Money"];
            cashValue?: components["schemas"]["Money"];
            premium?: components["schemas"]["Money"];
            /** @enum {string} */
            premiumFrequency?: "MONTHLY" | "QUARTERLY" | "ANNUALLY";
            beneficiaries?: components["schemas"]["BeneficiaryInput"][];
        };
        CoverageStatusView: {
            policyNumber?: components["schemas"]["PolicyNumberRef"];
            /** Format: date */
            asOf?: string;
            activeCoverages?: {
                /** @enum {string} */
                benefitType?: "DEATH" | "DISABILITY" | "CRITICAL_ILLNESS" | "MATURITY";
                sumAssured?: components["schemas"]["Money"];
            }[];
        };
        /**
         * Format: uuid
         * @description Opaque PartyId. Resolved via the party module's own API; never expanded inline.
         */
        PartyRef: string;
        Money: {
            /** @description Decimal string — never a binary float. */
            amount: string;
            /** @example TZS */
            currencyCode: string;
        };
        PolicyNumberRef: string;
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        PageMeta: {
            page?: number;
            pageSize?: number;
            totalElements?: number;
        };
        /** @description Poll target for async operations kicked off by a 202 response (e.g. surrender/maturity). */
        ProcessStatus: {
            processInstanceId?: string;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "COMPLETED" | "COMPENSATING" | "FAILED";
            errorDetails?: string | null;
            /**
             * Format: uri
             * @description Present once COMPLETED — link to the finalized resource.
             */
            resultLocation?: string | null;
        };
    };
    responses: {
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Semantically valid request rejected by a domain invariant (e.g. beneficiary shares don't sum to 100%). */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Missing/invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Optimistic-locking conflict or state-machine violation (e.g. surrendering an already-surrendered policy). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
