/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/policies/{policyNumber}/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List loans against a policy */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoanView"][];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Originate a new policy loan */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    policyNumber: components["schemas"]["PolicyNumberRef"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        requestedAmount: components["schemas"]["Money"];
                        /** @description Mobile money / bank disbursement destination */
                        payeeRef: string;
                    };
                };
            };
            responses: {
                /** @description Loan reservation confirmed and disbursement requested (async — see LoanDisbursed event / poll below) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoanView"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Requested amount exceeds available loan value, or the policy is not in force */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans/{loanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get loan detail and current outstanding balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    loanId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoanView"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans/{loanId}/repayments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a repayment (ad hoc or scheduled — RepaymentSchedule is optional per Deliverable 3 Rev 2 B3) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    loanId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amount: components["schemas"]["Money"];
                        paymentReference: string;
                    };
                };
            };
            responses: {
                /** @description Repayment accepted — pending payment gateway confirmation */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoanView"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoanView: {
            /** Format: uuid */
            loanId?: string;
            policyNumber?: components["schemas"]["PolicyNumberRef"];
            principalAmount?: components["schemas"]["Money"];
            outstandingBalance?: components["schemas"]["Money"];
            /** @description The rate from the most recent LoanInterestTerm entry (Deliverable 3 Rev 2, L1). */
            currentInterestRate?: number;
            /** @enum {string} */
            status?: "RESERVED_PENDING_ORIGINATION" | "ORIGINATED" | "DISBURSEMENT_REQUESTED" | "DISBURSED" | "REPAYING" | "SETTLED" | "FORCED_LAPSE_TRIGGERED" | "DISBURSEMENT_FAILED";
        };
        PolicyNumberRef: string;
        Money: {
            /** @description Decimal string — never a binary float. */
            amount: string;
            /** @example TZS */
            currencyCode: string;
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Optimistic-locking conflict or state-machine violation (e.g. surrendering an already-surrendered policy). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
