/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active products (catalog browsing) */
        get: {
            parameters: {
                query?: {
                    category?: "TERM_LIFE" | "ENDOWMENT" | "WHOLE_LIFE" | "ANNUITY" | "UNIT_LINKED" | "GROUP_LIFE" | "EDUCATION_SAVINGS";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductSummary"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new product definition (staff/actuarial only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProductRequest"];
                };
            };
            responses: {
                /** @description Product created (status DRAFT) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductSummary"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a new product version (staff/actuarial only)
         * @description Rejected with 422 if ifrsMeasurementModel is not set (Deliverable 3 Rev 2 — carried from Deliverable 2 Rev 2's mandatory-before-ACTIVE rule).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductVersionSpec"];
                };
            };
            responses: {
                /** @description Version published */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing ifrsMeasurementModel, incomplete rating-factor coverage, or a fund definition on a non-unit-linked product */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/active-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the version active as of a given date (used for quoting and rating) */
        get: {
            parameters: {
                query?: {
                    effectiveDate?: string;
                };
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProductSummary: {
            /** Format: uuid */
            productId?: string;
            productCode?: string;
            productName?: string;
            category?: string;
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "RETIRED";
            /** @example TZS */
            defaultCurrency?: string;
        };
        CreateProductRequest: {
            productCode: string;
            productName: string;
            /** @enum {string} */
            category: "TERM_LIFE" | "ENDOWMENT" | "WHOLE_LIFE" | "ANNUITY" | "UNIT_LINKED" | "GROUP_LIFE" | "EDUCATION_SAVINGS";
            /** @example TZS */
            defaultCurrency: string;
        };
        ProductVersionSpec: {
            /** @enum {string} */
            ifrsMeasurementModel: "GMM" | "PAA";
            /** Format: date */
            effectiveDate: string;
            /** Format: date */
            retirementDate?: string | null;
            ratingTable: {
                /** @enum {string} */
                factorType?: "AGE" | "OCCUPATION_CLASS" | "SMOKER_STATUS" | "SUM_ASSURED_BAND";
                band?: string;
                multiplier?: number;
            }[];
            benefitSchedule: {
                /** @enum {string} */
                benefitType?: "DEATH" | "DISABILITY" | "CRITICAL_ILLNESS" | "MATURITY" | "SURRENDER";
                calculationMethod?: string;
            }[];
            /** @description Only valid when category = UNIT_LINKED. */
            fundDefinitions?: {
                fundCode?: string;
                currentNav?: number;
            }[] | null;
        };
        ProductSnapshot: {
            /** Format: uuid */
            productId?: string;
            /** Format: uuid */
            productVersionId?: string;
            /** Format: date */
            effectiveDate?: string;
            /** @enum {string} */
            ifrsMeasurementModel?: "GMM" | "PAA";
            gracePeriodDays?: number;
            maxLoanToValuePercent?: number;
            /** @enum {string} */
            category?: "TERM_LIFE" | "ENDOWMENT" | "WHOLE_LIFE" | "ANNUITY" | "UNIT_LINKED" | "GROUP_LIFE" | "EDUCATION_SAVINGS";
            /** @description Raw JSON surrender-charge schedule from product_version.surrender_charge_schedule; null until a future milestone adds a way to author it. */
            surrenderChargeScheduleJson?: string | null;
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
