/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/underwriting/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a new business application for underwriting
         * @description Entry point for new business — agent portal, bancassurance portal, or staff back-office.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpenCaseRequest"];
                };
            };
            responses: {
                /** @description Case opened */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnderwritingCaseView"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/underwriting/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get underwriting case status and decision */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnderwritingCaseView"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/underwriting/cases/{caseId}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a risk assessment (medical/financial/occupational) against an open case
         * @description Staff-only (UNDERWRITER role). Not exposed to agents or customers.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitAssessmentRequest"];
                };
            };
            responses: {
                /** @description Assessment recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnderwritingCaseView"];
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/underwriting/cases/{caseId}/referral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refer a borderline case to a senior underwriter
         * @description Sets referralStatus separately from the final decision (Deliverable 3 Rev 2, U1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Referral recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OpenCaseRequest: {
            applicantPartyId: components["schemas"]["PartyRef"];
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            productVersionId: string;
            sumAssured: components["schemas"]["Money"];
            /** @description Structured Q&A responses; schema varies by product — see Deliverable 6 for the concrete field set. */
            medicalDisclosure?: Record<string, never>;
        };
        SubmitAssessmentRequest: {
            /** @enum {string} */
            assessmentType: "MEDICAL" | "FINANCIAL" | "OCCUPATIONAL";
            findings: string;
            riskScore?: number | null;
        };
        UnderwritingCaseView: {
            /** Format: uuid */
            caseId?: string;
            applicantPartyId?: components["schemas"]["PartyRef"];
            /** Format: uuid */
            productId?: string;
            /** @enum {string} */
            status?: "OPEN" | "IN_REVIEW" | "DECIDED";
            /** @enum {string} */
            referralStatus?: "NONE" | "REFERRED_TO_SENIOR" | "REFERRAL_RESOLVED";
            /** @enum {string|null} */
            decisionOutcome?: "ACCEPT" | "LOADED" | "DECLINED" | "POSTPONED" | null;
            decisionLoadingPercent?: number | null;
            decisionDeclineReason?: string | null;
            /** Format: date-time */
            decisionDecidedAt?: string | null;
        };
        /**
         * Format: uuid
         * @description Opaque PartyId. Resolved via the party module's own API; never expanded inline.
         */
        PartyRef: string;
        Money: {
            /** @description Decimal string — never a binary float. */
            amount: string;
            /** @example TZS */
            currencyCode: string;
        };
        /** @description RFC 7807 Problem Details, extended with errorCode and traceId. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://api.nlolo-lifeplatform.tz/problems/beneficiary-shares-invalid
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Stable machine-readable code for client-side branching, distinct from HTTP status. */
            errorCode?: string;
            /** @description Correlates to platform tracing/logs; always present, including on 5xx. */
            traceId: string;
            /** @description Field-level validation errors; present on 400 responses only. */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Validation failure (RFC 7807) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Missing/invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Semantically valid request rejected by a domain invariant (e.g. beneficiary shares don't sum to 100%). */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized — includes object-level authorization failures (e.g. a customer token requesting a policy whose policyholderPartyId doesn't match the token's party_id claim). Every customer- and agent-scoped endpoint below performs this check explicitly; role membership alone is never sufficient. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource does not exist, OR exists in a different tenant. Deliberately the same response either way — a 403 or a tenant-specific 404 would leak cross-tenant existence information. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Optimistic-locking conflict or state-machine violation (e.g. surrendering an already-surrendered policy). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key for safe retry of unsafe (POST) operations — most important on USSD/agent-portal flows over unreliable connectivity. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
