import { ArrowLeft } from 'lucide-react';
import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Field } from '@/components/Field';
import { PageHeader } from '@/components/AppShell';
import { StatusBadge } from '@/components/StatusBadge';
import { ErrorPanel, LoadingBlock } from '@/components/states';
import { Button } from '@/components/ui/button';
import { formatInstant } from '@/lib/dates';
import { isInitialLoad } from '@/store/createResourceSlice';
import { selectReturnDetail, useRegreportingStore } from '@/store/regreportingStore';
import { ReturnLinesList } from './ReturnLinesList';

/**
 * The "acts" half of drawer-previews-page-acts, though there is nothing to
 * act on here either: regenerating a return replaces its lines wholesale
 * (from the list page), and there is no in-place edit of a generated return.
 * `documentRef` is always null -- rendering a real TIRA submission artifact
 * is C2-blocked (RegulatoryReturnResponseDto's own javadoc).
 */
export function RegulatoryReturnDetailPage() {
  const { returnId = '' } = useParams();

  const detail = useRegreportingStore(selectReturnDetail(returnId));
  const loadDetail = useRegreportingStore((s) => s.loadDetail);

  useEffect(() => {
    if (returnId) void loadDetail(returnId);
  }, [returnId, loadDetail]);

  const view = detail.data;

  if (isInitialLoad(detail)) {
    return <LoadingBlock label="Loading return" />;
  }

  if (detail.data === null && detail.status === 'error' && detail.error) {
    return (
      <div className="px-6 pt-6">
        <BackLink />
        <ErrorPanel error={detail.error} onRetry={() => void loadDetail(returnId)} />
      </div>
    );
  }

  return (
    <>
      <div className="px-6 pt-6">
        <BackLink />
      </div>

      <PageHeader
        title={view?.returnType ?? 'Regulatory return'}
        description={view?.period}
        actions={view?.status && <StatusBadge kind="regulatoryReturn" value={view.status} />}
      />

      {view && (
        <div className="grid gap-5 px-6 pb-8 lg:grid-cols-[minmax(0,1fr)_320px]">
          <div className="space-y-5">
            <section className="rounded-lg border border-border bg-surface">
              <div className="border-b border-border px-4 py-3">
                <h2 className="text-sm font-semibold">Lines</h2>
              </div>
              <div className="p-3">
                <ReturnLinesList lines={view.lines} />
              </div>
            </section>
          </div>

          <div className="space-y-5">
            <section className="rounded-lg border border-border bg-surface">
              <div className="border-b border-border px-4 py-3">
                <h2 className="text-sm font-semibold">Return</h2>
              </div>
              <dl className="px-4 pb-2">
                <Field label="Generated" value={formatInstant(view.generatedAt)} />
                <Field label="Generated by" value={<span className="font-mono text-xs">{view.generatedBy}</span>} />
                <Field
                  label="Document ref"
                  value={view.documentRef ?? '—'}
                  note="Always null -- TIRA submission rendering is deliberately deferred"
                />
              </dl>
            </section>
          </div>
        </div>
      )}
    </>
  );
}

function BackLink() {
  return (
    <Button asChild variant="ghost" size="sm" className="-ml-2">
      <Link to=".." relative="path">
        <ArrowLeft />
        All regulatory returns
      </Link>
    </Button>
  );
}
