import { useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Field } from '@/components/Field';
import { PageHeader } from '@/components/PageHeader';
import { Panel } from '@/components/Panel';
import { StatusBadge } from '@/components/StatusBadge';
import { ErrorPanel, LoadingBlock } from '@/components/states';
import { formatInstant } from '@/lib/dates';
import { isInitialLoad } from '@/store/createResourceSlice';
import { selectReturnDetail, useRegreportingStore } from '@/store/regreportingStore';
import { ReturnLinesList } from './ReturnLinesList';

/** Where this record lives. Regulatory returns are staff-only. */
const BREADCRUMB = [{ label: 'Regulatory returns', to: '/staff/regulatory-returns' }];

/**
 * The "acts" half of drawer-previews-page-acts, though there is nothing to
 * act on here either: regenerating a return replaces its lines wholesale
 * (from the list page), and there is no in-place edit of a generated return.
 * `documentRef` is always null -- rendering a real TIRA submission artifact
 * is C2-blocked (RegulatoryReturnResponseDto's own javadoc).
 */
export function RegulatoryReturnDetailPage() {
  const { returnId = '' } = useParams();

  const detail = useRegreportingStore(selectReturnDetail(returnId));
  const loadDetail = useRegreportingStore((s) => s.loadDetail);

  useEffect(() => {
    if (returnId) void loadDetail(returnId);
  }, [returnId, loadDetail]);

  const view = detail.data;

  if (isInitialLoad(detail)) {
    return <LoadingBlock label="Loading return" />;
  }

  if (detail.data === null && detail.status === 'error' && detail.error) {
    return (
      <>
        {/* The bar renders on the error path too, so a return that fails to load keeps its
            heading and its way out instead of leaving the reader an error panel with nothing
            above it. */}
        <PageHeader breadcrumb={BREADCRUMB} title="Regulatory return" />
        <div className="px-6 pt-6">
          <ErrorPanel error={detail.error} onRetry={() => void loadDetail(returnId)} />
        </div>
      </>
    );
  }

  return (
    <>
      <PageHeader
        // Replaces a ghost button with a back arrow in its own strip above the bar.
        breadcrumb={BREADCRUMB}
        title={view?.returnType ?? 'Regulatory return'}
        description={view?.period}
        // `status`, not `actions`: a status is what the record IS, and `actions` is where a
        // control goes. The two are not interchangeable slots.
        status={view?.status && <StatusBadge kind="regulatoryReturn" value={view.status} />}
      />

      {view && (
        <div className="grid gap-5 px-6 pb-8 lg:grid-cols-[minmax(0,1fr)_320px]">
          <div className="space-y-5">
            <Panel title="Lines">
              <div className="p-3">
                <ReturnLinesList lines={view.lines} />
              </div>
            </Panel>
          </div>

          <div className="space-y-5">
            <Panel title="Return">
              <dl className="px-4 pb-2">
                <Field label="Generated" value={formatInstant(view.generatedAt)} />
                <Field label="Generated by" value={<span className="font-mono text-xs">{view.generatedBy}</span>} />
                <Field
                  label="Document ref"
                  value={view.documentRef ?? '—'}
                  note="Always null -- TIRA submission rendering is deliberately deferred"
                />
              </dl>
            </Panel>
          </div>
        </div>
      )}
    </>
  );
}

